services:
  - type: web
    name: um-tech-servicelayer
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: um-tech-db
          property: connectionString

databases:
  - name: um-tech-db
    plan: free
    databaseName: umtech_db
    user: umtech
